(setq graph '( 
	((A B C D) (A C B D) (A D B C) (B A C D))
	((A B D C) (A D B C) (A C D B) (B A D C))
	((A D B C) (A B D C) (A C B D))
	((A C B D) (A D B C) (A B C D) (C A B D))
	((A D C B) (A C D B) (A B C D))
	((A C D B) (A D C B) (A B D C) (C A D B))
	((C A B D) (A C B D) (C B A D))
	((C B A D) (C A B D) (B C A D))
	((C A D B) (C A D B))
	((B A C D) (A B C D) (B C A D))
	((B A D C) (A B D C))
	((B C A D) (B A C D) (C B A D)) 
)